### ISSUE TITLE
grunt removes new bower install --save depens from index.html

### ISSUE THREAD

**Issue by scottjason** [larsonjj/generator-yeogurt#100]
Hey Jake,

We're having some trouble installing new dependencies with bower. They're not being injected and when manually placed they're removed.

I've also tried adding a regular cdn script and that gets removed too. 

I tried putting the depend both inside and outside the grunt bower build and same result.

Right now we're hosting the lib instead to get around it and editing the grunt js hint config to ignore that script.

**Comment by scottjason** [comment]
Update: Same thing really but putting them outside of Grunt Build and they stay. Is the intended way to use bower with yeogurt? (adding colorpick.css like this and they don't get wiped) : 

      
            
            <link rel="stylesheet" href="/bower_components/normalize.css/normalize.css" />
            <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.css" />
            
        
            <link rel="stylesheet" href="/bower_components/colpick/css/colpick.css" />

**Comment by larsonjj** [comment]
Hey @scottjason,

You should be able to do something like this:

```
  <!-- build:css(client) styles/global.css -->
        <!-- bower:css -->
        <link rel="stylesheet" href="/bower_components/normalize.css/normalize.css" />
        <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.css" />
        <!-- endbower -->
        <link rel="stylesheet" href="/bower_components/colpick/css/colpick.css" />
  <!-- endbuild -->
```

Anything within the `<!-- bower:js -->` comments gets overwritten every time the `wiredep` task is run. So if [grunt-wiredep](https://github.com/stephenplusplus/grunt-wiredep) is not correctly reading the `colpick` library you have, then the above example I posted should work for now.

The other option involves telling your `wiredep` task where to look for `colpick` with the `overrides` option within your `grunt/config/util/wiredep.js` file. Here is an example of what might work:

```
// Add overrides option and tell wiredep where the colpick main file is
grunt.config.set('wiredep', {
  app: {
    options: {
      ...
      overrides: {
        'colpick': {
          'main': 'colpick.css'
        }
      }
      ...
    }
    ...
  }
}
```

For more information, try looking at the [wiredep](https://github.com/taptapship/wiredep) docs.
Let me know if this info helps.

**Comment by scottjason** [comment]
Thanks Jake .. what you suggested works perfectly (makes sense too):

"Anything within the  comments gets overwritten every time the wiredep task is run"

  
        
        <link rel="stylesheet" href="/bower_components/normalize.css/normalize.css" />
        <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.css" />
        
        <link rel="stylesheet" href="/bower_components/colpick/css/colpick.css" />
  


awesome!!

**Comment by larsonjj** [comment]
Glad it helped :+1: 
Closing out.
