### ISSUE TITLE
Using backbone and handlebars and getting this error when running build JST not defined

### ISSUE THREAD

**Issue by jessepinuelas** [larsonjj/generator-yeogurt#104]
Works fine on grunt serve issue is when running build

**Comment by larsonjj** [comment]
Thanks for raising the issue. I will look into it.

**Comment by larsonjj** [comment]
Can you please post the contents of your `.yo-rc.json` file? It is located in the root of your generated project (Please also remove any private FTP or Database info before posting). This will help me debug this much faster.

**Comment by jessepinuelas** [comment]
{
  "generator-yeogurt": {
    "config": {
      "projectName": "yeogurt-issue",
      "versionControl": "git",
      "useServer": false,
      "singlePageApplication": true,
      "jsFramework": "backbone",
      "jsTemplate": "handlebars",
      "jsOption": "browserify",
      "cssOption": "sass",
      "sassSyntax": "scss",
      "useJsdoc": false,
      "useKss": false,
      "useTesting": false
    },
    "version": "0.14.2"
  }
}

**Comment by larsonjj** [comment]
Sorry for the late response, I've been trying to recreate your issue, but it seems that everything is working as expected on my end. My recommendation would be to delete the `node_modules` folder and reinstall everything by running `npm install` again.

If that doesn't work, try upgrading the generator by running `npm install -g generator-yeogurt` and run the generator again with your posted settings.

 This will hopefully resolved your issue.

Closing out as I can't recreate this issue.
