### ISSUE TITLE
Road to v1.0.0

### ISSUE THREAD

**Issue by larsonjj** [larsonjj/generator-yeogurt#106]
Road to v1.0.0

Hello fellow Yeogurt users,

A lot of planning has gone into the next release of this generator and I felt it necessary to communicate what is in store for v1.0.0. Most of the feature-set for this generator has been completed, but there are a few things that need to be added to give generated applications a more complete workflow. Specifically testing:

- [x] End-to-end Testing (using [Protractor](http://angular.github.io/protractor/#/))
- [x] Server side Testing (using [Supertest](https://github.com/tj/supertest))

> Testing features Complete :+1:

The next thing needed is an update to the generated project structures. Currently, all projects are setup using the `Sock Drawer` method (files separated into 'type' folders):

Example:

```
client
├── scripts               # Scripts folder (All JS)
|   ├── index.js 
|   └── main.js
├── styles                # Styles folder (All Stylesheets)
|   └── main.scss
└── templates             # Templates folder (All templates)
| 	├── layouts
| 	|   └── base.jade
| 	└── index.jade
| 
└── test                  # Test folder (All tests)
    └── spec
        └── index.js
```

A better folder structure would use a `Filter by Feature` method (files separated by the feature they represent)

Example:

```
client
└── app
	├── index             # Homepage (All related files)
	|   ├── index.jade
	|   ├── index.js
	|   ├── index.spec.js
	|   └── index.scss
	├── layout            # Layout for app/site
	|   ├── base.jade
	|   └── base.scss
	├── main.js           # Main startup script
	└── main.scss         # Main stylesheet
```

This is a major change to current generated projects (hence the v1.0.0 bump), but should lead to much more maintainable and scalable projects. Here is some extra resources for learning about this type of structure:

- [John's Papa's Structuring Guidelines](http://www.johnpapa.net/angular-app-structuring-guidelines/). This is angular specific, but most of what's talked about can be used on any project.
- [Cliff Meyer's Code Organization](http://cliffmeyers.com/blog/2013/4/21/code-organization-angularjs-javascript). This is also angular specific, but gives good insight about Sock Drawer vs. Feature/Modular structure.

I have also setup separate issues to open up discussion on the proposed structure for each type of application this generator helps you build (Please use the links below to further discussion about specific project types):

- [Angular](https://github.com/larsonjj/generator-yeogurt/issues/108)
- [Backbone](https://github.com/larsonjj/generator-yeogurt/issues/109)
- [React + Flux](https://github.com/larsonjj/generator-yeogurt/issues/110)
- [Static Sites](https://github.com/larsonjj/generator-yeogurt/issues/111)
- [Express Server](https://github.com/larsonjj/generator-yeogurt/issues/107)

I'd love to hear everyone's thoughts on the proposed changes and welcome all feedback :+1:

Cheers! :beers:

Note: All work towards v1.0.0 is being done within the `development` branch. Beta coming soon!

**Comment by adamclerk** [comment]
:+1: to more modular scaleable solution!

**Comment by larsonjj** [comment]
Closing this in favor of [generator-neopolitan](https://github.com/larsonjj/generator-neopolitan) and `v1.0.0` of this generator (currently within the develop branch)
