### ISSUE TITLE
v1.0.0: React + Flux application restructure

### ISSUE THREAD

**Issue by larsonjj** [larsonjj/generator-yeogurt#110]
# React + Flux Application Restructuring

For Yeogurt v1.0.0, a revamp/restructure is needed for all generated applications. That being said, React + Flux projects need quite a bit of love in order to work well with a modular structure. Of course, I would like to keep the user base informed on the direction the project is taking when creating and scaling applications, so feel free to comment and leave feedback in this issue.

## Old Structure

Here is an example of what the generator currently produces for react + flux projects:

```
├── client
    ├── bower_components
    ├── scripts
    │   ├── actions                      # Flux actions
    │   │   ├── page.js
    │   │   └── routes.js
    │   ├── components
    │   │   ├── index.jsx                # Index page (required)
    │   │   └── layouts
    │   │       └── default.jsx
    │   ├── constants                    # Flux constants
    │   │   ├── defaults.js
    │   │   ├── page.js
    │   │   ├── payload-sources.js
    │   │   └── routes.js
    │   ├── dispatchers                  # Flux dispatcher
    │   │   └── default.js
    │   ├── main.js                      # Main bootstrap file
    │   ├── routes.js                    # Define all routes here
    │   └── stores                       # Flux stores
    │       ├── default.js
    │       └── page.js
    ├── images
    └── styles                          # Styles folder (All Stylesheets)
    |   └── main.scss                   # Main stylesheet (import everything to this file)
    ├── favicon.ico
    ├── index.html                      # Base template
    └── robots.txt
```

## New Proposed Structure

Here is an example of what could be produced for react + flux projects:

```
├── client
    ├── app                              # Application specific code
    |   ├── __tests__                    # Holds all tests for current folder
    |   |   ├── main.spec.js
    |   |   └── routes.spec.js
    |   ├── index                        # Homepage (all related files)
    |   |   ├── __tests__
    |   |   |   └── index.spec.js
    |   |   ├── index.jsx
    |   |   └── index.scss
    |   ├── layout                       # Layout structure for app
    |   |   ├── base.jsx
    |   |   ├── base.spec.js
    |   |   └── base.scss
    |   ├── modules                      # Reusable modules
    |   |   └── navbar
    |   |       ├── __tests__
    |   |       |   └── navbar.spec.js
    |   |       ├── navbar.jsx
    |   |       └── navbar.scss
    |   └── lib                          # Base Classes, Misc scripts, etc
    |   |   ├── __tests__
    |   |   |   └── store.spec.js
    |   |   └── store.js
    |   ├── main.js                      # Main bootstrap file
    |   ├── main.constants.js            # Main constants file (global constants)
    |   ├── main.dispatcher.js           # Main dispatcher file (handles all dispatched events)
    |   ├── main.actions.js              # Main actions file (global actions)
    |   ├── main.store.js                # Main store file (store global data)
    |   └── main.scss                    # Main stylesheet (import everything to this file)
    |   └── routes.js                    # Handles all routes
    ├── assets                           # Other static files (images, fonts, txt, etc)
    |   ├── images
    |   └── fonts
    ├── bower_components                 # Stores all bower files
    ├── vendor                           # Third-party (non-bower) files
    ├── favicon.ico
    ├── index.html                       # Base template
    └── robots.txt
```

This slightly updated structure is inspired by a few [angular] styleguides ([johnpapa](https://github.com/johnpapa/angularjs-styleguide), [mgechev](https://github.com/mgechev/angularjs-style-guide#directory-structure), and [toddmotto](https://github.com/toddmotto/angularjs-styleguide)). I realize that these cover mostly angular applications, but I have found that the structure they outline can be converted to be used with React + Flux quite well. I tried to pick some of my favorite features and techniques used between all of these great resources. Of course, I would like throw out some questions and get some feedback on the proposed changes.

## Proposed/Existing Sub-generators

Below are the proposed sub-generators that would be usable for projects creating React + Flux applications.

***Module***

  - Creates a new folder inside of `app/` folder (confgurable)
  - Creates new files based on name (ex. react)
    - `react.spec.js`
    - `react.jsx`
    - `react.scss`

***Flux***

  - Creates a new folder inside `modules/` (confgurable)
  - Creates new files based on name (ex. flux)
    - `flux.store.js`
    - `flux.action.js`
    - `flux.constant.js`
    - `flux.spec.js`

## Questions

Feel free to offer your opinion on these questions (or any others) within the comments section.

- Folders
  - Do their names make sense?
  - Do you like the structure?
- General
  - How can this be improved in your opinion?
  - Is anything confusing?
- Routing (What library should be used?)
  - [React Router](https://github.com/rackt/react-router)?
  - [Director](https://github.com/flatiron/director)? (Currently being used)

## Feedback

As stated above, I would love to get some feedback on what you all think about this new structure. I think it is a massive move forward to the old "sock-drawer" style structure, but there is always room for improvement.

Let me know what you think!

> NOTE: I continue to update this issue as more information comes in and feedback is gathered

**Comment by joshhornby** [comment]
Ever thought about an option for Reflux? Or any other flux style abstractions?

**Comment by bmanth60** [comment]
With the new structure, are there any intentions to allow Jest for React applications?

**Comment by larsonjj** [comment]
@joshhornby, I haven't really looked at other flux solutions as I wanted to stay as close to vanilla Facebook flux as possible.

@bmanth60 The new structure will allow for use with Jest by having test folders use the jest prefix and suffixes: `__tests__`. I haven't been able to successfully get Jest running with Yeogurt, but in theory it should work if you would like to add it to a generated project. I will look further into it after the 1.0 launch.

**Comment by larsonjj** [comment]
Closing this in favor of [generator-neopolitan](https://github.com/larsonjj/generator-neopolitan)
