### ISSUE TITLE
v1.0.0: Static site application restructure

### ISSUE THREAD

**Issue by larsonjj** [larsonjj/generator-yeogurt#111]
# Static Site Application Restructuring

For Yeogurt v1.0.0, a revamp/restructure is needed for all generated applications. That being said, Static Sites projects need quite a bit of love in order to work well with a modular structure. Of course, I would like to keep the user base informed on the direction the project is taking when creating and scaling applications.

## Old Structure

Here is an example of what the generator currently produces for static site projects:

```
├── client
|   ├── bower_components
│   ├── images
│   ├── scripts               # Scripts folder (All JS)
|   |   └── main.js
│   ├── styles                # Styles folder (All Stylesheets)
|   |   └── main.scss
│   └── templates             # Templates folder (All templates)
│   |   ├── layouts
|   |   |   └── base.jade     # Base template
|   |   └── index.jade        # Home page
|   ├── favicon.ico
|   └── robots.txt
└── test
    ├── scripts               # Compiled scripts to help with testing
    └── spec                  # JS unit tests
```

## New Proposed Structure

Here is an example of what could be produced for static site projects:

```
├── bower_components
├── vendor
└── src
|   ├── _images                # Images
|   ├── _layout                # Layout structure for app
|   |   └── base.jade
|   ├── _modules               # Reusable modules
|   |   └── navbar
|   |       ├── __tests__
|   |       |   └── navbar.spec.js
|   |       ├── navbar.jade
|   |       ├── navbar.js
|   |       └── navbar.scss
|   ├── _styles               # Global styles, mixins, variables, etc
|   |   └── main.scss         # Main stylesheet (import everything to this file)
|   ├── _scripts              # Global scripts, base classes, etc
|   |   └── main.js           # Main bootstrap file
|   ├── fonts                 # Fonts
|   └── index.jade            # Homepage template
├── favicon.ico
└── robots.txt
```

This slightly updated structure is inspired by a few other static site generators: ([Hexo](https://hexo.io/) and [Jekyll](http://jekyllrb.com/)). I tried to pick some of my favorite features and techniques used between all of these great resources such as: configuration file, copying all files and folders that aren't prefixed by an underscore (`_`). Of course, I would like throw out some questions and get some feedback on the proposed changes.

## Proposed/Existing Sub-generators

Below are the proposed sub-generators that would be usable for projects creating Static Sites.

Module
  - Asks for type of module
    - Page
    - Layout
    - Module
  - Creates a new folder inside of `app/` folder
  - Creates new files based on name (ex. static) [JS, Spec, and Style files are optional]
    - static.js           # JS specific to modules
    - static.spec.js      # Test file for JS
    - static.jade         # Template for module
    - static.scss         # Styles for module

## Questions

Feel free to offer your opinion on these questions (or any others) within the comments section.

- Folders
  - Do their names make sense?
  - Do you like the structure?
- General
  - How can this be improved in your opinion?
  - Is anything confusing?

## Feedback

As stated above, I would love to get some feedback on what you all think about this new structure. I think it is a massive move forward to the old "sock-drawer" style structure, but there is always room for improvement.

Let me know what you think!

> NOTE: I continue to update this issue as more information comes in and feedback is gathered

**Comment by markbrouch** [comment]
Am I correct in assuming that miscellaneous styles that don't belong to modules (like IE specific, etc) would go in the `lib` folder?

**Comment by larsonjj** [comment]
I would say if you need to override JS or CSS for IE specifically, you have a couple options:

1. Create a `main.ie.scss` file that handles the needed IE fixes. You can also create a `main.ie.js` file to handle needed JS fixes.
2. Create a `ie` or `legacy` folder within `app/` that houses all IE specific styles and javascript like so:

```
ie/
├── ie.scss
├── ie.js
└── ie.spec.js
```
3. You can put you IE file(s) within the `lib/` folder under an `ie` or `legacy` folder similar to #2.

It all depends on how much IE code you need, but I think all the above options could work. I think my preference would be #3.

What do you think @markbrouch?

**Comment by larsonjj** [comment]
Closing with release of [1.0.0](https://github.com/larsonjj/generator-yeogurt/tree/v1.0.0)
