### ISSUE TITLE
Using reactify

### ISSUE THREAD

**Issue by dipdipdip84** [larsonjj/generator-yeogurt#113]
Hi guys,

Thanks for this great generator.

Can I suggest you the inclusion of reactify and the use of .jsx extension in the browserify grunt task.

I tried to use some node modules that requires .jsx files without specifying extension so I had to modify the task.

```javascript
transform:  [ require('grunt-react').browserify, require('reactify') ],
        browserifyOptions: {
          debug: true,
          extensions: ['.js', '.json', '.jsx']
        },
```

**Comment by larsonjj** [comment]
Hey @dipdipdip84,

Glad you are getting good use of the generator :+1: 

As for adding reactify, I'm not exactly sure as to the extra benefit. As you can see in the example you provided, the `require('grunt-react').browserify` transform helps with the JSX conversion, so it looks like reactify is redundant and not needed. Could you clarify on the added benefit?

Thanks!

**Comment by larsonjj** [comment]
Haven't received a response in a while. hopefully my response was helpful.

Closing out.
