### ISSUE TITLE
how to add grunt-cache-bust to yeogurt-BB-SPA

### ISSUE THREAD

**Issue by scottjason** [larsonjj/generator-yeogurt#114]
Hey Jake,

We'd like to add something like this:

https://github.com/hollandben/grunt-cache-bust

to the build so when new new builds are pushed the client knows to get new script (like version number in file name.).

Is there a simple way to add this task?

**Comment by larsonjj** [comment]
Hey @scottjason,

Do you want cache busting for your static assets, or do you want to append some number to your files?
I guess you can do both using the [grunt-filerev](https://github.com/yeoman/grunt-filerev) plugin. It might not be exactly what you are looking for since the task will append an 8 character hash to each filename of your static assets, but it should work.

You can add a new file -- `filerev.js` to your `grunt/config/util/` folder and add the following content:

```js
'use strict';

var taskConfig = function(grunt) {

  grunt.config.set('filerev', {
    dist: {
      src: [
        '<%= yeoman.dist %>/scripts/{,*/}*.js',
        '<%= yeoman.dist %>/styles/{,*/}*.css',
        '<%= yeoman.dist %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
        '<%= yeoman.dist %>/styles/fonts/*'
      ]
    }
  }
};

module.exports = taskConfig;
```

Then just add the task to your `grunt/tasks/build.js` file like so:

```js
'use strict';

var taskConfig = function(grunt) {
  grunt.registerTask('build', 'Build a production ready version of your site.', [
    'clean:dist',
    'injector',
    'wiredep',
    'copy:dist',
    'concurrent:images',
    'concurrent:compile',
    'useminPrepare',
    'concat:generated',
    'cssmin',
    'autoprefixer:server',
    'filerev:dist',
    'usemin',
    'htmlmin:dist',
    'uglify',
    'clean:tmp'
  ]);
};

module.exports = taskConfig;
```

Let me know if that works out. :beers:

**Comment by scottjason** [comment]
Hey Jake! Thanks for writing that out. Yes, this solution would work great.

"Do you want cache busting for your static assets, or do you want to append some number to your files?"

Cache busting of static assets (for some reason I thought that appending a num to the file would result in the same thing).

We tried the above and got this error:


--

Running "useminPrepare:html" (useminPrepare) task
Going through client/index.html to update the config
Looking for build script HTML comment blocks
Warning: An error occurred while processing a template (Cannot read property 'dist' of undefined). Use --force to continue.

--

Do we need to update useminPrepare too?


--

https://github.com/yeoman/grunt-usemin/issues/291

There's this comment too from the above usemin issues which might be related? :


"I'm having this same problem. Line 166, as referenced by @Feijk works, but only if I put grunt.config, not if I put grunt.config.get().

Seems like it should work the latter way, given what the grunt docs say. Anyone else see this?

I'm on grunt-usemin v2.1.1 and grunt v0.4.4, by-the-way."

**Comment by scottjason** [comment]
Jake we actually just got rid of the error ( just by changing the yeoman to yeogurt in the new taskConfig ). It's not appending any of the strings to the filenames so looking into that now.

**Comment by larsonjj** [comment]
Great :+1: 

Glad you got it all working.
