### ISSUE TITLE
Connecting to inspector

### ISSUE THREAD

**Issue by mildfuzz** [larsonjj/generator-yeogurt#115]
I can see that the server is being broadcast to debugger on port 5858 but I can't seem to connect with it. What am I missing?

**Comment by larsonjj** [comment]
Hey @mildfuzz 

Are you using [node-inspector](https://github.com/node-inspector/node-inspector)?

If so, follow this [guide](https://github.com/node-inspector/node-inspector#advanced-use) to debug your node application.

Basically, Node's debugger is going to run on the default port 5858, and you can boot up a node-inspector server to access dev tools for your node application via URL. ex. `http://127.0.0.1:8080/debug?port=5858`

**Comment by larsonjj** [comment]
Received no response for quite some time. Hopefully my above answer has helped.
Closing out.
