### ISSUE TITLE
Deployment workflow

### ISSUE THREAD

**Issue by gtelljohann** [larsonjj/generator-yeogurt#116]
Hi, it would be great if you gave some documentation of the way you intend people to deploy a yeogurt generated app to somewhere like heroku

**Comment by oddurs** [comment]
+1

**Comment by larsonjj** [comment]
Hey @gtelljohann and @oddurs,

This is a great idea and I am currently working on documentation for deploying to heroku for the v1.0.0 release. If you have successfully implemented a yeogurt application on any PaaS, please feel free to share your process/success here in this thread as it may help me finish up the documentation faster.

Cheers! :beers:

**Comment by joshuapekera** [comment]
Hey @larsonjj,
I am trying to add [grunt-build-control](https://github.com/robwierzbowski/grunt-build-control) to the build task so I can push only what is in `/dist` to a `production` branch. I was trying to add a subtask to `build` called `deploy` to trigger everything. Grunt keeps throwing errors. Do you have any ideas for the best way to set this up?

Here is my current build.js.
```
// `grunt build`
// Builds out an optimized site through (but not limited to) minification of CSS and HTML,
// as well as uglification and optimization of Javascript, and compression of images.

'use strict';

var taskConfig = function(grunt) {
  grunt.registerTask('build', 'Build a production ready version of your site.', function(target) {

    grunt.task.run([
    'clean:dist',
    'injector',
    'wiredep',
    'copy:dist',
    'concurrent',
    'useminPrepare',
    'concat:generated',
    'cssmin',
    'autoprefixer:dist',
    'usemin',
    'htmlmin:dist',
    'uglify',
    'clean:tmp'
  ]);

  if (target === 'deploy') {
    return grunt.task.run(['buildcontrol'])
  }
};

module.exports = taskConfig;
```
Here is the buildcontrol.js file that is in util
```
// Configuration for Build Control task(s)
// Deploys the dist directory to a production branch
'use strict';

var taskConfig = function(grunt) {

  grunt.config.set('buildcontrol', {
    dist: ['<%= yeogurt.dist %>'],
    commit: true,
    push: true,
    message: 'Built %sourceName% from commit %sourceCommit% on branch %sourceBranch%'
  },
    pages: {
      options: {
        remote: 'git@github.com:joshuapekera/joshuapekera.git',
        branch: 'production'
      }
    }
  )
};

module.exports = taskConfig;
```

**Comment by larsonjj** [comment]
Closing this as it only relates to pre v1.0.0 version of Yeogurt.

**Comment by pgangwani** [comment]
@larsonjj Hey Jake,
I need guide too. Could you share the link ?
