### ISSUE TITLE
Marko templating

### ISSUE THREAD

**Issue by patbegg** [larsonjj/generator-yeogurt#120]
Any plans to have Marko templates as an option?
Great boilerplate, much appreciated.

**Comment by larsonjj** [comment]
Hey @patbegg,

Glad to hear you enjoy using yeogurt :+1: 

As for Marko templating, I don't have any plans for supporting it. It might be beneficial for a [Guide](https://github.com/larsonjj/generator-yeogurt/tree/master/docs/guides) to be written on how to add Marko templating to a generated yeogurt project. If you have successfully implemented Marko, I would gladly except a PR with a step-by-step guide.

**Comment by larsonjj** [comment]
Feel free to open up a PR if you get around to adding a guide for using Marko templates with Yeogurt.
Closing out.
