### ISSUE TITLE
Wiredep and bower components

### ISSUE THREAD

**Issue by pagoad** [larsonjj/generator-yeogurt#123]
Hi.
I would like to change  bower_components path and add "/" before url, when wiredep put all .js files into jade template.
I tried to do this in wiredep.js but it does not work.
I would like to chenge from:
          // bower:js
             script(src='bower_components/jquery/dist/jquery.js')

to:
           // bower:js
              script(src='/bower_components/jquery/dist/jquery.js')

**Comment by larsonjj** [comment]
Hi @pagoad,

Could you post your `.yo-rc.json` file (located in the root of your project)? That would help me debug this faster.

Thanks!

**Comment by pagoad** [comment]
{
  "generator-yeogurt": {
    "config": {
      "projectName": "Project",
      "versionControl": "none",
      "useServer": true,
      "dbOption": "none",
      "singlePageApplication": false,
      "htmlOption": "jade",
      "jsOption": "browserify",
      "cssOption": "less",
      "useJsdoc": false,
      "useKss": false,
      "useTesting": true,
      "testFramework": "mocha"
    },
    "version": "0.14.1"
  }
}

**Comment by larsonjj** [comment]
By default, all injected javascript and css paths start with a `/`, so I'm not sure why your wiredep task isn't doing this correctly. This is the piece of code you should see in your `grunt/config/util/wiredep.js` task:

```js
// Make sure everything has an absolute path (starts with '/')
fileTypes: {
  jade: {
    replace: {
      js: 'script(src=\'/{{filePath}}\')',
      css: 'link(rel=\'stylesheet\', href=\'/{{filePath}}\')'
    }
  }
},
```
As you can see from the above code snippet, there is a `replace` object that allows you to change how the paths are injected.

Hopefully this helps. If you have more questions, I would recommend you raise an issue upstream to the [grunt-wiredep](https://github.com/stephenplusplus/grunt-wiredep) and/or the [wiredep](https://github.com/taptapship/wiredep) repos themselves.

Closing out.
