### ISSUE TITLE
GitLab Integration Plugin

### ISSUE THREAD

**Issue by drewbeta** [larsonjj/generator-yeogurt#129]
I would like to see a GitLab integration plugin where an architect can create component specs in GitLab's issue tracker, then stub out the site structure directly from the GitLab data to be passed on to the dev team.

**Comment by larsonjj** [comment]
@drewbeta,

Closing for now as this will most likely not be implemented within Yeogurt. Would be cool to see another npm module interface with Gitlab and the yeogurt subgenerator api though.
