### ISSUE TITLE
Replace Grunt with Gulp for performance

### ISSUE THREAD

**Issue by vlkz** [larsonjj/generator-yeogurt#130]

**Comment by larsonjj** [comment]
@vlkz, thanks for the suggestion.

At this time, there is no plan to switch over to gulp as it would be a significant rewrite. I do agree that performance could be improved over the use of grunt by switching to gulp, but it also looks like [v1.0](https://github.com/gruntjs/grunt-next) of grunt will also use streams which could alleviate some of the performance bottlenecks soon.
