### ISSUE TITLE
Feature: generate sprites from icons

### ISSUE THREAD

**Issue by Bogdaan** [larsonjj/generator-yeogurt#133]
How about add sprite generator ( like https://github.com/Ensighten/grunt-spritesmith ) and ***icons*** folder ?

**Comment by larsonjj** [comment]
@Bogdaan, Thanks for the suggestion!

That plugin looks pretty awesome. I will look into adding it.
Of course, a PR is welcome as well :+1:

**Comment by larsonjj** [comment]
Hey @Bogdaan,

I realize this is from a VERY long time ago, so I'm going to close it.
If you find some extra time to write a guide on how to implement `gulp-spritesmith` within a project and PR it, that would be awesome!

Closing for now.
