### ISSUE TITLE
Use of compass

### ISSUE THREAD

**Issue by ilicmarko** [larsonjj/generator-yeogurt#136]
I have a hard time making this work with compass. I tried editing `sass.js` but nothing:

```javascript
  grunt.config.set('sass', {
    options: {
      compass: true
    },
    server: {
      options: {
        precision: 10,
        outputStyle: 'nested',
        sourceMap: true,
        includePaths: [
          '<%= yeogurt.client %>/bower_components',
          '<%= yeogurt.client %>/styles/'
        ]
      },
      files: {
        '<%= yeogurt.tmp %>/styles/main.css': '<%= yeogurt.client %>/styles/main.{scss,sass}'
      }
    },
    dist: {
      options: {
        precision: 10,
        outputStyle: 'compressed',
        sourceMap: false,
        includePaths: [
          '<%= yeogurt.client %>/bower_components',
          '<%= yeogurt.client %>/styles/'
        ]
      },
      files: {
        '<%= yeogurt.dist %>/styles/main.css': '<%= yeogurt.client %>/styles/main.{scss,sass}'
      }
    }
  });
```

The error I get:
```
file to import not found or unreadable: compass
```
Maybe I should add it to includePaths but what path should I add?

**Comment by larsonjj** [comment]
Hey @ilicmarko, Compass is not supported in the version of [node-sass](https://github.com/sass/node-sass) provided by this generator. You can read more about it [here](https://github.com/sass/node-sass/issues/54). If you absolutely need compass, then you will need to switch out the `grunt-sass` plugin with `grunt-contrib-sass` which uses the ruby compiler. Here is a [guide](https://github.com/larsonjj/generator-yeogurt/blob/master/docs/guides/ruby-sass.md) on how to do that.

Hopefully that helps.
