### ISSUE TITLE
grunt serve: jsdoc failed

### ISSUE THREAD

**Issue by jolugama** [larsonjj/generator-yeogurt#138]
When i write: grunt serve:

jit-grunt: Plugin for the "jsdoc" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "jsdoc:server" failed. Use --force to continue.

Aborted due to warnings.

**Comment by larsonjj** [comment]
Could you post your `.yo-rc.json` file? This will help me debug the issue you are having.

**Comment by larsonjj** [comment]
Closing due to non-response. As of `v1.0.0`, jsdoc is no longer supported (very buggy)
