### ISSUE TITLE
main.js Error: [$injector:unpr] Unknown provider: a

### ISSUE THREAD

**Issue by jolugama** [larsonjj/generator-yeogurt#139]
there isnt config:
'use strict';

// Declare app level module which depends on views, and components
angular.module('englishTrainer2', [
  'ngRoute'
])

.config(['$routeProvider', function($routeProvider) {
  $routeProvider.otherwise({redirectTo: '/'});
}]);

console.log('Welcome to Yeogurt!');

when i write:
 .when('/', {
            templateUrl: 'home/home.html',
            controller: 'HomeCtrl'
        })
not found it!!!. 
thank you!.

**Comment by robmpreston** [comment]
Yep, having this same problem - Created the default angular app using yeogurt, immediately tried to use grunt serve:build and this is the error. Anyone alive out there?

**Comment by larsonjj** [comment]
Could you post your `.yo-rc.json` file? This will help me debug the issue you are having.

**Comment by larsonjj** [comment]
Closing due to non-reponse. Also, AngularJS is no longer supported as of [v1.0.0](https://github.com/larsonjj/generator-yeogurt/blob/master/CHANGELOG.md#v100)
