### ISSUE TITLE
jquery not found (404(

### ISSUE THREAD

**Issue by tylersloan** [larsonjj/generator-yeogurt#141]
Hey Jake,

Yeogurt has been pretty nice since I yo'd it earlier today. I am having a bit of an issue with having it find and recognize jQuery, though. I see in the readme what to do, but that hasn't worked.

I have installed jQuery with Bower, included it myself, and tried to link to it a variety of ways and it just can't be found. Anything extra I should be doing that I'm missing?

Thanks for the generator and thanks for the help.

yo-rc.json http://cl.ly/bxeb

**Comment by tylersloan** [comment]
I figured it out. My fault. 

Added `import $ from 'jquery'` and realized I didn't need ot link with a script tag.

I see my mistake but still feels a little confusing. What if I don't want my main.js and jQuery to be concatted? (Or any other vendor js for that matter?)

**Comment by larsonjj** [comment]
Hey @tylersloan,

Glad you figured it out :+1: 

I haven't found an elegant way to separate vendor files from my main bundle, but adding a new task can help:

```js
gulp.task('browserify:vendor', () => {
  let dest = path.join(__dirname, taskTarget, dirs.scripts.replace(/^_/, ''));
  browserify(
    path.join(__dirname, dirs.source, dirs.scripts, '/vendor.js'), {
    debug: true,
    transform: [
      require('envify'),
      require('babelify')
    ]
  }).bundle()
    .pipe(vsource(path.basename('vendor.js')))
    .pipe(buffer())
    .pipe(plugins.sourcemaps.init({loadMaps: true}))
      .pipe(gulpif(production, plugins.uglify()))
      .on('error', plugins.util.log)
    .pipe(plugins.sourcemaps.write('./'))
    .pipe(gulp.dest(dest))
    .pipe(browserSync.stream());
});

...
// Vendor Scripts
      gulp.watch([
        path.join(__dirname, dirs.source, dirs.scripts/, 'vendor.js')
      ], ['browserify:vendor']);
```

You'll also need to add the `browserify:vendor` task to your `gulp build` and `gulp serve` tasks.

Hope this helps!

**Comment by tylersloan** [comment]
I will give that a shot. In the meantime, if I want to add, say, Modernizr and Owl Carousel, what would I put in the "globals" section of .exlintrc? I tried `'owlCarousel': true,` and tried importing into my main.js. No dice there either. Just unsure of the workflow regarding third party libraries.

**Comment by larsonjj** [comment]
If you want to use third-party libraries that are not available on NPM, you can use bower and the [debowerify](https://www.npmjs.com/package/debowerify) transform:

` npm install debowerify --save`

Then add it to the gulp browserify task:
```
transform: [
      require('envify'),
      require('babelify'),
      require('debowerify')
    ]
```

```js
// main.js
import $ from 'jquery';
import owlCarousel from 'owl.carousel';
```

see if that helps.

**Comment by larsonjj** [comment]
Hey @tylersloan, 
Just wrote up some more information about using [non-commonjs libraries](https://github.com/larsonjj/generator-yeogurt/tree/develop#using-non-commonjs-modules-with-browserify-shim) as well as using [bower](https://github.com/larsonjj/generator-yeogurt#using-bower-must-be-used-with-browserify-shim). They should bring some light on how to solve your issues.
