### ISSUE TITLE
Files inside **/vendor/** are still linted

### ISSUE THREAD

**Issue by dustine** [larsonjj/generator-yeogurt#142]
Hello! I've been enjoying using this generator so far, even if it took a bit to wrap my head around as a few of the components (Jade) were new for me. 

Now, I've ran into an issue when trying to use some imported third party files files (in this case a [javascript game library](craftyjs.com)) in the folder `src/scripts/vendor`. While `gulp deploy` worked all fine, trying to do any build action failed under a spam of lint errors, pointing at the vendor folder.

## (Hackish) Testcase

Just for testing if it was really that, or something related to the library I was using, I did the following in a brand new project:

1. Create a project with all the default options
2. Download the latest jquery 2.x, both compressed and uncompressed
3. Move the obtained .js files to`src/scripts/vendor`
   - Also tried on these following folders separately: `src/vendor` and `src/_scripts/vendor`
4. Run `gulp eslint`

![image](https://cloud.githubusercontent.com/assets/8994495/8704565/a5c50044-2b1b-11e5-9fb7-0b9499decb90.png)

Problem still occured. I'm running the generator on Win8.1, if that helps (and the reason it's so ugly).

### .yo-rc.json

*`.yo-rc.json` file contents*:
```json
{
  "generator-yeogurt": {
    "config": {
      "projectName": "Sample",
      "htmlOption": "jade",
      "cssOption": "sass",
      "sassSyntax": "scss",
      "testFramework": "jasmine"
    },
    "version": "1.0.1"
  }
}
```

## Possible solution

I also found out that, at least for me, changing the `gulpfile.babel.js` on the `'eslint'` task so that the `'!'` was outside the `path.join` fixed the issue:
```javascript
gulp.task('eslint', () => {
  gulp.src([
    path.join(__dirname, 'gulpfile.js'),
    path.join(__dirname, dirs.source, '**/*.js'),
    // Ignore all vendor folder files
    '!' + path.join(__dirname, '**/vendor/**', '*')
  ])
  .pipe(browserSync.reload({stream: true, once: true}))
  .pipe(plugins.eslint({
    useEslintrc: true
  }))
  .pipe(plugins.eslint.format())
  .pipe(plugins.if(!browserSync.active, plugins.eslint.failAfterError()));
});
```

No idea if it's the most ideal solution or if it works at all for others beyond me.

Any further support would be appreciated, and thank you for the hard work!

**Comment by larsonjj** [comment]
I am not able to replicate this issue on OSX, but it seems that it may be a Window specific problem regarding pathing. I will look into it.
