### ISSUE TITLE
Install a previous version(0.13.3) of yeogurt.

### ISSUE THREAD

**Issue by pavanhl** [larsonjj/generator-yeogurt#144]
My project had an requirement to use nodejs, mongodb, express and swig. So chose yeogurt(0.13.3) to build my whole project. Now i am trying to setup my project using yo yeogurt and its a completely new setup. Can someone help me to get the previous version of yeogurt.

**Comment by larsonjj** [comment]
npm install -g generator-yeogurt@0.14.6

That should get you to the last version that supported your previous project setup.
