### ISSUE TITLE
error creating project on Windows

### ISSUE THREAD

**Issue by carlillos** [larsonjj/generator-yeogurt#147]
Hi,
There is some problem when I create some project.
I get:

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\node
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for C:\Users\nicolas\AppData\Local\Temp\npm-6056-
ee852a\registry.npmjs.org\browser-sync-ui\-\browser-sync-ui-0.5.15.tgz
npm ERR! Expected: c3a684313aaa379783231d826a5c6d8e3b5da128
npm ERR! Actual:   4dafd1face4763f2e7127aefa8a5f056360a97de
npm ERR! From:     https://registry.npmjs.org/browser-sync-ui/-/browser-sync-u
0.5.15.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\sites\dir2\npm-debug.log

Everything looks ready! Get started by running "gulp serve".

**Comment by larsonjj** [comment]
Hi @carlillos,

This is most likely due to some missing dependencies. Check out [http://www.browsersync.io/docs/#windows-users](http://www.browsersync.io/docs/#windows-users) for info on how to solve this issue.

Closing as this is specific to BrowserSync and now Yeogurt.
