### ISSUE TITLE
Option to trigger maps in the production

### ISSUE THREAD

**Issue by OnkelTem** [larsonjj/generator-yeogurt#149]
I believe it should be configurable to have or not map files in the production build.

**Comment by larsonjj** [comment]
This could be a useful feature. What do you think the api for this should be?

A new option (`--no-maps`) could be added that tells Browserify and Sass/Less/Stylus gulp tasks to remove sourcemaps:

```
gulp --production --no-maps
```

It could also work in development

```
gulp serve --no-maps
```

Thoughts?

**Comment by OnkelTem** [comment]
@larsonjj 
Yeah, I like this approach.

But after some further thinking I now don't see that need in this. Really, nobody forces you to *upload* .map files, right? So only if you gonna gzip the ```build``` as is then you probably need this option.
In other cases one can easily add `--exclude=` option like:
```
 tar czf build.tar.gz build --exclude="*.map"
```

That said, with the additional option it seems just fine.

**Comment by larsonjj** [comment]
Yeah @OnkelTem,

I'm starting to think that the extra `--no-maps` option isn't super useful as it is very easy to ignore/exclude the `*.map` files as you pointed out. I think for now, I will just close this out.

If more people bring this ask up, we can revisit the `--no-maps`option addition to the codebase.

Sound good?

**Comment by OnkelTem** [comment]
Agreed.
