### ISSUE TITLE
Exec attribute (+x) set on README.md and robots.txt

### ISSUE THREAD

**Issue by OnkelTem** [larsonjj/generator-yeogurt#152]
For some reason I get `README.md` and `robots.txt` files with `exec` attr set:

```
$ls -la
-rw-r--r--  1 fantomas fantomas 1150 Sep 23 14:54 favicon.ico
drwxrwxr-x  2 fantomas fantomas 4096 Sep 23 14:54 images
-rw-r--r--  1 fantomas fantomas 1125 Sep 23 14:54 index.html
-rwxrwxrwx  1 fantomas fantomas 1180 Sep 23 14:54 README.md
-rwxrwxrwx  1 fantomas fantomas   77 Sep 23 14:54 robots.txt
drwxrwxr-x  2 fantomas fantomas 4096 Sep 23 14:54 styles
```

**Comment by larsonjj** [comment]
Hmm very interesting.

I'll try and look into this when I get some time. Otherwise a PR is most welcome :+1:

**Comment by OnkelTem** [comment]
I forgot that those files were actually a symlinks. So this is a gulp issue, follow-up is here: https://github.com/gulpjs/gulp/issues/1273
