### ISSUE TITLE
"imagemin-pngquant" Error

### ISSUE THREAD

**Issue by jamesabels** [larsonjj/generator-yeogurt#155]
I keep getting this error when I npm install and then gulp serve, installing imagemin-pngquant seems to fix the problem. 

I would contribute, but I'm not 100% sure how generators work, but I think just adding 

"imagemin-pngquant": "^4.2.0",

to the package.json should fix the issue, if it isn't already there. 

Or it could just be this machine for some reason. 

Anyways, keep up the great work, this is my favorite generator by far!

**Comment by larsonjj** [comment]
Hey @jamesabels,

The latest version of imagemin-pngquant is 4.2.0 and every generated project has this line included in the package.json file:

```
"imagemin-pngquant": "~4.2.0"
```

So I would guess that there was some error on the initial `npm install` when you ran the generator. Then when you ran it again, it fixed the error. For future reference, if you run into similar issues, deleting your node_modules folder and re-running `npm install` usually does the trick.

I haven't been able to replicate this issue, so I'm closing this out. Glad you were able to resolve it though :+1:

**Comment by jamesabels** [comment]
That's what I figured, but thought I would bring it up just  in case. 

Thanks for looking into it, and keep up the good work!

🙈🙉🙊😍😍😍
