### ISSUE TITLE
The jquery and bootstrap not included

### ISSUE THREAD

**Issue by bagusflyer** [larsonjj/generator-yeogurt#156]
I run the bower install for bootstrap:

> bower install bootstrap4-dist --save

And include the css and js in my base.nunjucks file like this

> ```
> <link rel="stylesheet" href="../../bower_components/bootstrap4-dist/dist/css/bootstrap.css">
> <link rel="stylesheet" href="{{baseUrl}}styles/main.css"/>
> <script src="{{baseUrl}}scripts/main.js"></script>
> ```
> 
>    ......
>     {% block scripts %}{% endblock %}
>     <script src="../../bower_components/bootstrap4-dist/dist/js/bootstrap.min.js"></script>

The path is correct but it shows the files can't be loaded. So I changed the link to cdn. The bootstrap style works. But it shows another error message:

> Uncaught Error: Bootstrap's JavaScript requires jQuery

Isn't JQuery preinstalled by the generator? Please help. Thanks.

**Comment by bagusflyer** [comment]
In the document you mentioned that we can use bootstrap like this:

> @import 'node_modules/bootstrap-sass-official/scss/bootstrap';

My question is where to install those files ? I know how to install through bower but not npm. But you've preinstalled the Jquery in npm already. Should I remove it first? Thanks.

**Comment by DDaems** [comment]
This is how i got it working:
`npm install bootstrap-sass --save`
>@import node_modules/bootstrap/dist/css/bootstrap

Do not add a extention to it. Else it won't work. I though it was as simple as just adding it to the template file like:
```
block append scripts/styles
  filename
´´´ 
Boy was i wrong! Anyway i haven't figured out how to get the javascript file to work. But i think we will need use browserify-shim.to make it work. Honestly i don't want to use it. Is there any easyer way to do this?

**Comment by Gibranhiko** [comment]
Hello we are trying to setup a enviroment with bootstrap and jquery, a couple of doubts:

1. Is jquery already pre-installed?
2. I'm getting this error while trying to download bootstrap using npm? 
![error](https://cloud.githubusercontent.com/assets/10965876/12400319/e59e2df6-bde4-11e5-8a78-5199f7659dc2.PNG)

**Comment by DDaems** [comment]
If i remember correctly jQuery is by default installed. If you want to make sure, check the generated `package.json` file. And here is the info on how to include it: [howto](https://github.com/larsonjj/generator-yeogurt#scripts)

2) You can ignore the warning.

**Comment by Gibranhiko** [comment]
I managed to install bootstrap by using bower:
![bootstrap](https://cloud.githubusercontent.com/assets/10965876/12405355/f650d9d6-be08-11e5-8428-687810919b08.PNG)

Then I reference bootstrap styles in my main.scss 
![bootstrap styles](https://cloud.githubusercontent.com/assets/10965876/12405366/1abfadb0-be09-11e5-9019-b6dd040abd9f.PNG)

Only thing missing is bootstrap.js I tried your previous walkthrough, but was not able to make it work, now I can use bootstrap styles but stuff like carousel does not work, any ideas?

**Comment by DDaems** [comment]
Try this:

`npm install browserify-shim --save-dev`

package.json
```
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browser": {
    "bootstrap": "./bower_components/bootstrap-sass/assets/javascript/bootstrap.js",
    "jquery": "./node_modules/jquery/dist/jquery.js"
  },
  "browserify-shim": {
    "jquery": "$",
    "bootstrap": {
      "exports": null,
      "depends": "jquery:jQuery"
    }
  },
```
main.js
>import 'jquery';
import 'bootstrap-sass';

**Comment by Nekomant** [comment]
TW Bootstrap 4.0.0.alpha6 and 4.0.0-beta required Popper.js
I use browserify-shim
```
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browser": {
    "bootstrap": "./node_modules/bootstrap/dist/js/bootstrap.js",
    "popper.js": "./node_modules/popper.js/dist/popper.js"
  },
  "browserify-shim": {
    "bootstrap": {
      "exports": "bootstrap",
      "depends": [
        "jquery:jQuery",
        "popper.js:Popper.js",
        "tether:Tether"
      ]
    }
  }
```
but in console i see error
```
Uncaught Error: Bootstrap dropdown require Popper.js
```

**Comment by sahibhuseyn** [comment]
I think updating package.json or bower.json manually for every third-party dependecies. Is there any way for making automatise this issue?
And second question is how i change my styles, scripts and images folder directory while build process?
-In static html file i did this way for the related question "" But I have no any idea doing this in nunjucks file

**Comment by enaros** [comment]
hey @Nekomant did u find a workaround to that?

**Comment by Nekomant** [comment]
@enaros nope. Popper dependency appear in BS 4.0.0 Beta. 
Now i use strict `"bootstrap": "4.0.0-alpha.6",` in dependencies section of package.json and
```javascript
  "browser": {
    "bootstrap": "./node_modules/bootstrap/dist/js/bootstrap.js"
  },
  "browserify-shim": {
    "bootstrap": {
      "exports": null,
      "depends": [
        "jquery:jQuery",
        "tether:Tether"
      ]
    }
  }
```
for browser-shim.

**Comment by sahandii** [comment]
I think I've tried to add+initialize three different kind of JS-libraries to my projects now, and I keep running into the same problem.

`**Uncaught ReferenceError: (*) is not defined**`

I check the scripts.js file after a save, and I see that the libraries get added proper to the file, with the 'depends' in the works. But still, I can't initialize any of the libraries. Why is this happening?
