### ISSUE TITLE
Issue with assets version

### ISSUE THREAD

**Issue by Bogdaan** [larsonjj/generator-yeogurt#158]
Problem:
when gulp generate new assets - clients populate old assets from cache.

**Comment by larsonjj** [comment]
Hi @Bogdaan,

Could you be more specific? Is this happening on production builds, or when running the development server?

**Comment by larsonjj** [comment]
Closing due to no response.

**Comment by Bogdaan** [comment]
@larsonjj see "long term caching"
How to reproduce:
1. setup production web-server config (for example nginx)
```
location ~* \.(?:css|js|png|jpg|ico)$ {
  expires max;
  access_log off;
  add_header Cache-Control "public";
}
```
2. build and deploy (version 1)
3. visit you page
4. build and deploy (version 2)
5. visit you page (oops - **assets from cache**)

LTC with webpack - https://webpack.github.io/docs/long-term-caching.html

LTC with Gulp:
a)  https://www.npmjs.com/package/gulp-rev
b) custom build pipe (hash name for js/css/images)
