### ISSUE TITLE
Add Yaml support?

### ISSUE THREAD

**Issue by OnkelTem** [larsonjj/generator-yeogurt#159]
What do you think about supporting yaml files in the data directory?

**Comment by OnkelTem** [comment]
First shot. Now you can mix `json` and `yaml` files in the data directory.

**Comment by larsonjj** [comment]
Hey @OnkelTem,

Thanks for bringing this up and submitting a PR :+1: 
I think adding YAML support would be great. I do however think the both JSON and YAML should be supported at the same time, not necessarily something that you have to choose when generating a project.

I'm open to discussion about it though. Thoughts?

**Comment by OnkelTem** [comment]
Ah, I see your point. That's just a bad wording :) JSON is supported always while YAML is added if you select this option at project setup. I decided to keep it separate because of new packages, you know.

As for whether to include it always or not - it's up to you :)

**Comment by larsonjj** [comment]
Yeah I think it's not too heavy to just add the YAML converter dependencies to every project. I can see where it would be kind of annoying to not select YAML at the start of your project and find out you need to use some YAML files later.

If you could remove the extra templating stuff I think that would be best.

**Comment by larsonjj** [comment]
YAML support has been added as of `v1.5.0`. Thanks for your PR and help :+1:
