### ISSUE TITLE
Gulp LESS task causes full page refresh instead of using the streamed CSS

### ISSUE THREAD

**Issue by webxl** [larsonjj/generator-yeogurt#163]
Simple fix in less.js:32: `.pipe(browserSync.stream({match: '**/*.css'}));`

 See https://www.browsersync.io/docs/gulp/#gulp-sass-maps

**Comment by larsonjj** [comment]
Thanks for reporting. PR welcome :+1:

**Comment by larsonjj** [comment]
This fix has been implemented as of `v1.5.0`. Thanks for your PR :+1:
