### ISSUE TITLE
PostHTML support

### ISSUE THREAD

**Issue by Grawl** [larsonjj/generator-yeogurt#166]
Like [PostCSS](https://github.com/postcss/postcss), [PostHTML](https://github.com/posthtml/posthtml) is a growing technology and a community filling up with plugins to process HTML through AST tree with JS code.

It's already [have plugins](http://maltsev.github.io/posthtml-plugins/)
- for [including](https://github.com/posthtml/posthtml-include) one template into another, 
- [extend](https://github.com/maltsev/posthtml-extend) them on top of each other part,
- read images and [add their sizes](https://github.com/maltsev/posthtml-img-autosize) into `<img>` elements,
- [improve accessibility of tabs](https://github.com/jonathantneal/posthtml-aria-tabs) and [add missing `alt` attributes](https://github.com/ismamz/posthtml-alt-always),
- [minify html](https://github.com/maltsev/htmlnano) in modular way and [inline any assets](https://github.com/jonathantneal/posthtml-inline-assets) you want,
- maintain [BEM classnames](https://github.com/rajdee/posthtml-bem) or [use CSS modules](https://github.com/admdh/posthtml-modular-css),
- and even [use PostCSS](https://github.com/posthtml/posthtml-postcss) on inline styles.

It's highly important to implement this technology right now.

**Comment by larsonjj** [comment]
Hey @Grawl,

Thanks for bringing this new lib to my attention. Seems pretty cool.
What's even more awesome is that it should work within Yeogurt very easily. I don't really see a need to add it here out of the box, but a Guide on how to get it to work might be helpful.

Would you be willing to write a guide on how to add PostHTML to the jade/nunjucks gulp tasks?

**Comment by Grawl** [comment]
Maybe. Has no enough time, sorry.

**Comment by larsonjj** [comment]
Closing due to non-activity.
