### ISSUE TITLE
jquery bootstrap wrong loading order?

### ISSUE THREAD

**Issue by inspmoore** [larsonjj/generator-yeogurt#169]
Dear peoples of the Interwebs!
I've manage to load jQuery and Bootstrap using require.js.
My main.js:
`'use strict';

var $ = require('jquery');
var Link = require('../_modules/link/link');
require('bootstrap-sass');

$(function() {
  new Link(); // Activate Link modules logic
  console.log('Welcome to Yeogurt!');
});`

Both of them load but bootstrap is constantly spiting out an error: "Error: Bootstrap's JavaScript requires jQuery".
I'm not sure but i think that they load in an invalid order. Is there a way to modify it?

**Comment by larsonjj** [comment]
Hey @inspmoore,

Looks like this issue has come up before. Try taking a look [Here](https://github.com/larsonjj/generator-yeogurt/issues/156) and see if it helps.

Cheers :beers: !
