### ISSUE TITLE
[feature] Add twig.js template engine

### ISSUE THREAD

**Issue by namerci** [larsonjj/generator-yeogurt#175]
I would like to add https://github.com/justjohn/twig.js/ as a choice to template engine. It's almost same syntax as Nunjucks, but have better highlights in IDE's.

**Comment by larsonjj** [comment]
Thanks for the feature request, unfortunately twig is basically identical to nunjucks, so I will not be adding code to support it. More details in [your PR](https://github.com/larsonjj/generator-yeogurt/pull/176)
