### ISSUE TITLE
"No" answer doesn't work for "Do you want to use this yo.rc file" question

### ISSUE THREAD

**Issue by JimTheMan** [larsonjj/generator-yeogurt#177]
I had a yo.rc 5 folders up. Yeoman asks me if I wasnt to use it, and I choose no. However, the files still get scaffolded in the directory 5 levels up.

**Comment by larsonjj** [comment]
Hey @JimTheMan 

Yeoman generators look for `.yo-rc.json` files to know where to generate files. The question you answered `No` to, is asking if you would like to use the existing configuration within that file, NOT if you want files generated elsewhere. So the files will be generated where-ever it finds that `.yo-rc.json` file.

If you want to generate a project in a subfolder of an existing project, you should create a blank `.yo-rc.json` file in the directory you expect the files to be generated in:

```js
// .yo-rc.json
{}
```

Or you will need to delete the `.yo-rc.json` file within the parent directory. Unfortunately these are the only two options currently.

You can check out this [issue](https://github.com/yeoman/yeoman/issues/635) for more details.

Closing out.
