### ISSUE TITLE
Support for plain HTML files

### ISSUE THREAD

**Issue by A92hm** [larsonjj/generator-yeogurt#179]
I know this generator supports Jade, Handlebars, and some other preprocessors.
I was wondering if there was an option for using plane HTML? If not I can make it and make a pull request.

**Comment by daveobriencouk** [comment]
As far as I can see the support is there.

I've just created a file called `test.html` on a local install, and the page renders in the browser as expected. Have you tried to do this your end?

**Comment by A92hm** [comment]
Sorry for the late response.
Yes It does. I was talking about `"htmlOption":"none"`. That way It will not include any jade files nor any jade related dependencies.

Also are you guys not doing the css or JS injections anymore? I guess my question is should I put all the other style and JS files under the _modules folder and reference (require) them from main.*css and main.js

**Comment by larsonjj** [comment]
Hey @A92hm,

Yeogurt projects no longer use injections for `.scss` or `.js` files. To answer your question: Yes you will need to import your `.scss` and `.js` files from the `_modules` folders into your `main.scss` and `main.js` files respectively.

"htmlOption": "none" no longer exists, so if you are planning on using HTML, I would suggest choosing `nunjucks` as it handles HTML very well and give you some extra programmatic power (variables, imports, etc).

Hopefully this helps!

**Comment by larsonjj** [comment]
Closing out due to lack of response/activity. Feel free to reopen if you have more to add @A92hm.
