### ISSUE TITLE
jQuery does not work at all

### ISSUE THREAD

**Issue by MaximilianLloyd** [larsonjj/generator-yeogurt#181]
i have this code 

// Main javascript entry point
// Should handle bootstrapping/starting application

'use strict';

import $ from 'jquery';

$(() => {
  let licenses = $('.license-item');

  licenses.click(() => {
    $(this).hide();
  });

});

I have tried with many other functions such as .css and .animate, they do not work either.

**Comment by larsonjj** [comment]
Hey @MaximilianLloyd,

I can't seem to replicate the issue you are having, can you post the contents of your `.yo-rc.json` file (it's a hidden file found in the root folder of your project). This will help me diagnose the issue quicker.

In the meantime, sometimes deleting the `node_modules` folder and then re-running `npm install` in the root folder of your project can fix some issues. Feel free to try that out.

**Comment by seniorjono** [comment]
I am having the same issue, except with ES5.

I don't appear to be able to get Jquery to work at all, I am deleting the node_modules and reinstalling them as I am writing this, but if I can shed some light on this issue I will do my best to help with error logs etc.

**Comment by seniorjono** [comment]
{
  "generator-yeogurt": {
    "config": {
      "projectName": "GSK",
      "htmlOption": "nunjucks",
      "jsPreprocessor": "none",
      "cssOption": "sass",
      "sassSyntax": "scss",
      "testFramework": "none"
    },
    "version": "1.5.3"
  }
}

This is the contents of my yo-rc file.
