### ISSUE TITLE
Error when calling method which defined in main.js from index.jade file

### ISSUE THREAD

**Issue by eko24** [larsonjj/generator-yeogurt#182]
Hello,

Perhaps this one is a dumb question because I'm more than sure that I'm missing something.

Here is my main.js:

```javascript
// Main javascript entry point
// Should handle bootstrapping/starting application

'use strict';

var $ = require('jquery');
var Link = require('../_modules/link/link');

$(function() {
  new Link(); // Activate Link modules logic
  console.log('Welcome to Yeogurt!');
});

var log = function() {
  console.log(1)
}
```

and element from index.jade:
```jade
button(onclick="log()") Log
```

Here is error I see in DevTools console :
![error screenshot](http://i.imgur.com/6xPBRxl.png)

Thanks in advance !

**Comment by larsonjj** [comment]
Hey @eko24,

All Javascript is run through Browserify which makes sure that logic doesn't leak into the global (i.e. `window`) scope. If you would like to use the `log()` function, you need to explicitly attach it to the window scope like so:

```js
window.log = function() {console.log(1)};
```

A better way to handle your button click (so as to not attach everything to `window`) would be to use jQuery to query your button and then attach an event listener:

***Jade***
```jade
// Jade
button.myButton
```
***JS***
```js
var log = function() { console.log(1);}
// Wait for DOM to load
$(function() {
  $('.myButton').on('click', function() { log(); });
});
```

Hope this helps! 🍻

**Comment by eko24** [comment]
Thank you @larsonjj, now it's clear for me :v:
