### ISSUE TITLE
Autoreload doesn't reload when I changes .less/.jade/.js files in _modules folder

### ISSUE THREAD

**Issue by eko24** [larsonjj/generator-yeogurt#184]

**Comment by eko24** [comment]
Ok, I found that adding `"modules": "_modules",` in package.json `config.directories` fixes this issue

**Comment by eko24** [comment]
Just noticed that `modules` was already added, so in fact I'm just duplicated it, wonder how it is even works :smile: 
`directories` value:
```
"directories": {
      "source": "src",
      "destination": "build",
      "temporary": "tmp",
      "//": "Directories relative to `source` directory",
      "modules": "_modules",
      "layouts": "_layouts",
      "images": "_images",
      "styles": "_styles",
      "scripts": "_scripts",
      "modules": "_modules",
      "data": "_data"
    },
```

**Comment by larsonjj** [comment]
Hey @eko24,

If you remove that duplicate key, does it  still work? If so, then I think this is a non-issue.

**Comment by eko24** [comment]
@larsonjj today `gulp serve` stopped watch _modules again. When I removed duplicate key and restarted `gulp serve` - it started work fine.
I think it is local issue, but I'll let you know if this happens again.
Thank you for your attention :+1:

**Comment by oninross** [comment]
I am facing the issue now.  I have `"modules": "_modules"` in my `package.json` and its not working
