### ISSUE TITLE
Generate none minified css and js

### ISSUE THREAD

**Issue by TamerTawfik** [larsonjj/generator-yeogurt#185]
I want to customize the gulp --production so it generates none minified version of css and js files
Thanks

**Comment by larsonjj** [comment]
Hey @TamerTawfik,

If you don't want css to be minified, you can comment out/delete [this line](https://github.com/larsonjj/generator-yeogurt/blob/master/app/templates/gulp/es6/sass.js#L35) that refers to `cssnano` within your `gulp/{sass,less,stylus}.js` file. For unminified JavaScript, you can do the same to [this line](https://github.com/larsonjj/generator-yeogurt/blob/master/app/templates/gulp/es6/browserify.js#L56) and [this line](https://github.com/larsonjj/generator-yeogurt/blob/master/app/templates/gulp/es6/browserify.js#L57) which refer to `uglify` located within the `gulp/browserify.js` file.

Let me know if this helps, cheers!

**Comment by TamerTawfik** [comment]
Thanks for your help @larsonjj
