### ISSUE TITLE
Can't access site.data variable

### ISSUE THREAD

**Issue by eko24** [larsonjj/generator-yeogurt#187]
Hello
I have menu.json file in _data folder:
```json
[
  {"url":"","index":"0"},
  {"url":"about","index":"1"},
  {"url":"portfolio","index":"2"},
  {"url":"expertise","index":"3"},
  {"url":"contact","index":"4"}
]
```

I'm trying to log site.data.menu from main.js:
```javascript
console.log(site.data.menu)
```

And have this error:
![console error](http://i.imgur.com/QbsjkoU.png)

Can someone help me with this please ?

**Comment by eko24** [comment]
**UPDATE**
I can access menu.json file from jade with this code:
```jade 
site.data.menu[1].url
```

**Comment by eko24** [comment]
TL;DR
_data files accessible only from templates.

Ok, just figured out it's simple [RTFM](https://github.com/larsonjj/generator-yeogurt#data-files "Read the fucking manual!") situation :smile: 
Sorry for disturbing :hand:

**Comment by eko24** [comment]
If you want use files from _data folder in your .js files, you can achieve it with:
```javascript
var _menu = require('../_data/menu.json');
```

Works like a charm !

**Comment by driera** [comment]
Just facing this! Thanks @eko24!

**Comment by eko24** [comment]
You're welcome @driera
