### ISSUE TITLE
HTML Minification & Jquery not working

### ISSUE THREAD

**Issue by seniorjono** [larsonjj/generator-yeogurt#189]
I can't currently get my HTML to be minified when serving, or building, nor has Jquery ever worked from default within the generator.

**Comment by mradzinski** [comment]
I can confirm HTML minification is not working. JQuery is working just fine though, have you tried declaring `global.$ = global.jQuery = require('jquery');` in your main.js file?

**Comment by seniorjono** [comment]
Hi, I will try the jquery declaration  first thing in the office tomorrow,
all the same would you be able to advise on how to get HTML minification
working or an alternative?

Regards,
Jono

**Comment by mradzinski** [comment]
@seniorjono I'm working on fixing the HTML minification as we speak. I'll try pushing a PR once I get it to work.

**Comment by mradzinski** [comment]
Looks like gulp *nunjucks* task is missing the `collapseWhitespace: true` parameter. It should look like this:

```javascript
    .pipe(plugins.htmlmin({
      collapseBooleanAttributes: true,
      conservativeCollapse: true,
      removeCommentsFromCDATA: true,
      removeEmptyAttributes: true,
      removeRedundantAttributes: true,
      collapseWhitespace: true <-- This was missing
    }))
```
