### ISSUE TITLE
Nunjucks: Working with arrays?

### ISSUE THREAD

**Issue by katrinkerber** [larsonjj/generator-yeogurt#190]
I am using Nunjucks and am trying to work with arrays as outlined in [their docs](https://mozilla.github.io/nunjucks/templating.html#for), but the array just prints out as text and the for loop is empty.

Am I missing a step or are arrays not supported?

**Comment by larsonjj** [comment]
Hey @katrinkerber,

Apologies for the late response. I haven't been able to work on this project for quite some time. Hopefully you were able to figure out the issue you were having with Nunjucks arrays. If not, maybe I can help a bit here.

To answer your question, Arrays do work just fine. If you would like to test them out, you can add a new `menu.json` file to your `_data` folder in a generated project and give it these contents:

```
{
  "items": [{ "title": "foo", "id": 1 }, { "title": "bar", "id": 2}]
}
```

Then go to the `src/index.nunjucks` file and add the following code anywhere within the `<div class="main-container">`:

```
{% for item in site.data.menu.items %}
  <li>{{ item.title }}</li>
{% else %}
  <li>This would display if the 'item' collection were empty</li>
{% endfor %}
```

Then you should see 2 list items spit out in your browser labeled `foo` and `bar`.

Let me know if this was helpful. Closing this out for now.
