### ISSUE TITLE
Add 'gulp-sass-glob' package

### ISSUE THREAD

**Issue by davidbwaters** [larsonjj/generator-yeogurt#191]
I've recently started using this in my workflow and find it fits with the workflow/opinion of the generator and thought I'd suggest it as a feature request.  Wasn't going to fork for such a small change, but I just installed and added `.pipe(plugins.sassGlob())` before the SASS stream.  

This allows SASS to be auto-imported  from folders with globs.  Imports that need to be loaded first can be specified normally, but a common directory structure usually makes this almost drop-in.  Saves so much time, for example, when adding a new component to a 'styles/components' directory, adding the path to 'main.scss' isn't necessary.  This applies to mixins and many typical SASS workflow components.

**Comment by larsonjj** [comment]
Hey @davidbwaters,

Thanks for bringing this to my attention. `sass-glob` seems like a cool project 👍 
Unfortunately, I won't be adding this to the project as it can cause some serious confusion as to import order. By default `styles/**/*.scss` would load each file based on alphabetical order, but that might not be desired (more reasoning [here](http://stackoverflow.com/a/4779432)). Plus, less and stylus glob support is inconsistent even with plugins.

I'm glad `gulp-sass-glob` is working well for you, but I don't think it would be a good fit for this project currently. On the bright side, it seems as though this plugin is very easy to add, so if people are looking for this functionality, they can add it to their projects without much effort.

**Comment by davidbwaters** [comment]
I can see how it could cause confusion, in some cases.  I assume anyone using this generator has a grasp of a Gulp workflow.  It seems natural to me to view it the same way scripts in a Gulpfile included.  Core scripts are specified explicitly first and the rest are just globbed afterwards, as are many things in Gulp.
