### ISSUE TITLE
How to disable testing feature of it?

### ISSUE THREAD

**Issue by jitendravyas** [larsonjj/generator-yeogurt#194]

**Comment by larsonjj** [comment]
@jitendravyas,

Been staring at this question for some time now and still do not understand exactly what you are asking. If you want to disable unit testing altogether, just be sure to select `None` in the `Which JavaScript testing framework would you like to use?` section.

Example:
<img width="488" alt="screen shot 2017-02-27 at 12 04 11 am" src="https://cloud.githubusercontent.com/assets/3893845/23350471/6aabd900-fc80-11e6-8a0d-5089732d74ea.png">


Let me know if this helps. Closing out for now.
