### ISSUE TITLE
How to replace Jade on Pug

### ISSUE THREAD

**Issue by parkersonik** [larsonjj/generator-yeogurt#197]
That does not make it is impossible to work with Pug...
please help...

**Comment by larsonjj** [comment]
Hi @parkersonik ,

Pug is still in beta, so I am holding off on an upgrade until it is fully released.
Jade is still perfectly usable in the meantime though. Hopefully pug will be released soon!

**Comment by parkersonik** [comment]
Thanks for the reply...
