### ISSUE TITLE
[Feature Request]: convert yeogurt to generate pug instead of jade

### ISSUE THREAD

**Issue by oninross** [larsonjj/generator-yeogurt#199]
Based from their website (https://github.com/pugjs/pug#rename-from-jade), they have changed jade to pug.  Would be nice if your generator followed the same :)

**Comment by larsonjj** [comment]
Hi @oninross,

Pug is still in beta, so I am holding off on an upgrade until it is fully released.
Jade is still perfectly usable in the meantime though. Hopefully pug will be released soon!
