### ISSUE TITLE
Implement better tool for png compression

### ISSUE THREAD

**Issue by bichotll** [larsonjj/generator-yeogurt#204]
My colleague argued that the images were way too heavy and compared the output with what TinyPNG would provide.
It was around 75% lighter in size.

https://tinypng.com/

I think that could be implemented easily with gulp using gulp-imagemin as a plugin?

I might do so if I have a bit of time.

**Comment by bichotll** [comment]
Sorry, I didn't realise it was not an open source tool.
In any case, I understand that can be optimised.

**Comment by larsonjj** [comment]
Hey @bichotll,

I realize this is a super late response, but wanted to give some insight here before closing this issue. This generator uses gulp-imagemin to process images and there are quite a few plugins that can be used based on your requirements (see https://www.npmjs.com/search?q=imagemin). These plugins can easily be installed via npm and added the imagemin gulp task to a generated project.

Cheers 🍻
