### ISSUE TITLE
Switch Jade to Pug

### ISSUE THREAD

**Issue by ehne** [larsonjj/generator-yeogurt#208]
jade has been renamed to pug and is no longer being maintained. please fix.

**Comment by larsonjj** [comment]
There is a PR open for this conversion: #196, but waiting for Pug to have an official release (currently 2.0.0-rc.4) before upgrading from Jade.

See my comment here for more info: https://github.com/larsonjj/generator-yeogurt/pull/196#issuecomment-282642340.
