### ISSUE TITLE
Change dest folder structure

### ISSUE THREAD

**Issue by sahibhuseyn** [larsonjj/generator-yeogurt#209]
I want to change folder structure in build folder. My folder structure will be:
- build
    -frq-templates
       --assets
           ---styles
          --- scripts
      
    - index.html

I can not customize my folder structure, is there any way to do this?

**Comment by Dan503** [comment]
edit the `dest` of files in the gulp tasks. so for example in sass task the `dest` is currently 
````
path.join(taskTarget, dirs.styles.replace(/^_/, ''));
````

Change it to this:
````
path.join(taskTarget, 'assets', dirs.styles.replace(/^_/, ''));
````

This change needs to be applied to the browserify and imagemin tasks as well.
