### ISSUE TITLE
how to exclude some modules?

### ISSUE THREAD

**Issue by joneldiablo** [larsonjj/generator-yeogurt#211]
if I want put a variable in package.json
`
{
...
  "config":{
     ...
     "dev":true
  }
}
`
in the .jade files you can read this variable and exclude a module easily with a
`if config.dev`
`  +module`  
but in the js files, how could you exclude the loading of that script if dev == false?

**Comment by Dan503** [comment]
Very easily. Import your package.json file into your javascript file

```````js
import pkg from '../../package.json'
```````

That path is a relative path so it might be different based on your folder structure.

After importing the pkg variable you can access the `dev` variable like this

```````js
if (pkg.config.dev){
    // Do dev only stuff
}
```````

**Comment by Dan503** [comment]
oh except it will still bundle that dev javascript into your final js file. It just won't run so it's extra page weight.

There isn't really an easy way to conditionally bundle js files. The easiest way I know of is to create a seperate js file that holds dev only code and reconfigure the browserify task to look at both. Doing that is far from "easy" though.

**Comment by joneldiablo** [comment]
another question, using babel, how can I use enviroment variable? meabe with these I can filter scripts, for ´build --production´, and meabe add ´build --staging´

**Comment by Dan503** [comment]
I don't think you can pass the Yeogurt `args` variable directly into the js compiler (the `args` variable holds all your `--argumentName` arguments).

You CAN pass it into your pug files though. 

So to do that I would pass the `args` variable into the `locals` Pug compiler options. I would then place a `<script>` tag on the page like this:

````
script
  | var args = !{JSON.stringify(args)}
````
