### ISSUE TITLE
Test framework keep being created although I've chosen none

### ISSUE THREAD

**Issue by framelita** [larsonjj/generator-yeogurt#217]
I've checked inside .yo-rc.json and it also shows none

`{
  "generator-yeogurt": {
    "config": {
      "projectName": "Lenovo Ultraslim",
      "htmlOption": "jade",
      "jsPreprocessor": "es6",
      "cssOption": "sass",
      "sassSyntax": "scss",
      "testFramework": "none"
    },
    "version": "2.0.1"
  }
}`

Is there any other setting that I can change to make sure it's not creating test folder? Thanks!

**Comment by larsonjj** [comment]
Fixed in #226
