### ISSUE TITLE
Access site.data in a module template?

### ISSUE THREAD

**Issue by saun4app** [larsonjj/generator-yeogurt#218]
As far as I can tell, we have access to site.data from pages (e.g., src/page_name/index.nunjucks), but not modules (e.g., _modules/link/link.nunjucks).  Is there a way to access site.data from a module?

Thank you.

**Comment by larsonjj** [comment]
Hey @saun4app,

While you can't access `site.data` within a nunjucks/jade module directly, you can pass the data to the module if you would like. Here is an example:

```
{{link.content({
    href: 'https://github.com/larsonjj/generator-yeogurt#yeogurt-generator---',
    text: 'documentation',
    site: site
})}}
```
