### ISSUE TITLE
Passing data from a class to template?

### ISSUE THREAD

**Issue by saun4app** [larsonjj/generator-yeogurt#219]
Is there a way to pass data from a class (Link in _modules/link/link.js) the the template (_modules/link/link.nunjucks)?

Thank you.

**Comment by larsonjj** [comment]
Hey @saun4app, I realize this response is super late. Apologies for that.
Unfortunately you cannot pass data from a module `.js` file to a `.nunjucks/.pug` file directly.

Not sure what the use case would be here, so going to close this out. Feel free to reopen if you'd like to discuss further.
