### ISSUE TITLE
Add asset/css/js rev'ing  

### ISSUE THREAD

**Issue by anchovy** [larsonjj/generator-yeogurt#220]
#featureRequest

Hi - great too for my workflow which allows me to quickly create static sites, but I'd love to see rev'ing in the project as well i.e. renaming, as a last build function, all the assets + updating the build css/js/html to reference these new file names.

i.e. main.{css,js,map} > main.45reer3ef35.{css,js,map}
image.{png,svg,gif,etc....} > image.45ff34242we.{png,svg,gif,etc....}

Would also need to be able to not rev certain files, based on folder location.

Thanks in advance.

**Comment by larsonjj** [comment]
Asset revisioning is now added in v3.0.0
