### ISSUE TITLE
Browser update notification

### ISSUE THREAD

**Issue by Grawl** [larsonjj/generator-yeogurt#70]
I suggest to prompt user to include [Browser-update.org](http://www.browser-update.org/) package into Bower by default as a dependency as it highly recommended to use on any website to notify users of deprecated browsers that they opportunities can be .

Now I found these Bower packages:

- [zenopopovici/browser-update](https://github.com/zenopopovici/browser-update) – have a lot of options but redirects to whatbrowser.org by default
- [rogeriopradoj/browser-update](https://github.com/rogeriopradoj/browser-update) – looks like official and it is a morror of code.google.com/p/browser-update that looks like official too

There is also [UpdateMyBrowser.org](http://UpdateMyBrowser.org) to look into.

**Comment by larsonjj** [comment]
I think may not really be needed since there is already a call out for upgrading to a better browser in every generated project. @Grawl, If you submit a PR on a better solution, that would be awesome.

Otherwise, closing out for now.
