### ISSUE TITLE
Autopolyfiller?

### ISSUE THREAD

**Issue by Grawl** [larsonjj/generator-yeogurt#72]
[Autopolyfiller](https://github.com/azproduction/autopolyfiller) is like [Autoprefixer](https://github.com/ai/autoprefixer), but for JavaScript polyfills. It scans your code and applies only required polyfills. [Live example](http://azproduction.ru/autopolyfiller).

**Comment by larsonjj** [comment]
I haven't really had much time to work on extra guides (with the large amount of work being done for v1.0.0) and won't for a while. @Grawl, If you find the time to create a PR for a guide on adding an autopolyfiller, I would greatly appreciate it.

Closing out.
