### ISSUE TITLE
How about a langing page for Yeogurt?

### ISSUE THREAD

**Issue by Grawl** [larsonjj/generator-yeogurt#74]
Hey dawg I heard it's good to have a landing for yo' GitHub project, so let's generate a static site with yo' static site generator!

We will need to add some parts of readme into template I think so we need to generate `readme.md` with this parts too (or do it someway smarter).

**Comment by larsonjj** [comment]
Development of landing page has started [here](https://github.com/yeogurt/yeogurt.github.io). Please continue discussion and development there.
