### ISSUE TITLE
Account Boilerplate for Express Server

### ISSUE THREAD

**Issue by larsonjj** [larsonjj/generator-yeogurt#77]
Being able to generate a fully functional express server with account authentication would be extremely useful. Obviously this use case if very popular based on the [Hackathon Starter](https://github.com/sahat/hackathon-starter) project. So, I think it would be beneficial to allow users the ability to do so.

Types of authentication:
***Default***
- Local Email and Password

***Optional***
- Facebook
- Twitter
- Google

***Maybe***
- Passwordless Token

**Comment by larsonjj** [comment]
This had now been added. Check it out in the new [release](https://github.com/larsonjj/generator-yeogurt/releases/tag/v0.13.0)

**Comment by joshhornby** [comment]
Would love to see some social login features
