### ISSUE TITLE
Feature request: Option to auto generate and inject module specific JS CSS

### ISSUE THREAD

**Issue by fusionstrings** [larsonjj/generator-yeogurt#81]
This would be awesome if while creating new tamplate (page /module) it asks to create module specific  JS and SASS / CSS in designated folder if `--folder` argument is passed or in default CSS, JS folder.

It should be able to auto inject these as well. It would be great for plug and play reusable components for yeogurt projects. So for example if certain folder is removed all the injection shall go away. Most this already happens but JS, CSS doesn't reside in same directory and it's required to create them manually. 

Also newly created JS files should be added to RequireJS/Browserify config.

My context is molecular composition on line of patternlab.io to generate static site.

**Comment by larsonjj** [comment]
I left this issue open for quite a while now, So I apologize for the slow response. I just wanted to inform you that for the v1.0.0 version of this generator (currently in development), module subgenerators will be usable and should help accomplish your request in this issue. You can follow and/or comment on the new proposed changes [here](https://github.com/larsonjj/generator-yeogurt/issues/106)

Closing out.
