### ISSUE TITLE
Use Wiredep

### ISSUE THREAD

**Issue by Grawl** [larsonjj/generator-yeogurt#86]
Remember my request at #75? I found a better solution to do this: [grunt-wiredep](http://stephenplusplus.github.io/grunt-wiredep/)!

Easy as a pie.

We can cleanup and automatize all Bower dependencies imports.

For example, in Jade:

`templates/layouts/base.jade`

```jade
// build:js(client) scripts/global.js
script(src='/bower_components/jquery/dist/jquery.js')
script(src='/bower_components/foundation/js/vendor/fastclick.js')
script(src='/bower_components/foundation/js/vendor/jquery.cookie.js')
script(src='/bower_components/foundation/js/vendor/placeholder.js')
script(src='/bower_components/foundation/js/foundation/foundation.js')
// endbuild
```

becomes

```jade
// build:js(client) scripts/global.js
// bower:js
// endbower
// endbuild
```

And after `wiredep` task it fills with all installed Bower components:

```jade
// bower:js
script(src='../../bower_components/modernizr/modernizr.js')
script(src='../../bower_components/jquery/dist/jquery.js')
script(src='../../bower_components/fastclick/lib/fastclick.js')
script(src='../../bower_components/jquery.cookie/jquery.cookie.js')
script(src='../../bower_components/jquery-placeholder/jquery.placeholder.js')
script(src='../../bower_components/foundation/js/foundation.js')
// endbower
```

using `main` section of every `bower.json` into `bower_components`.

We can specify `cwd` and other cool options for do it properly. For example, we can provide `exclude` list for things like `foundation.css`. It's complex but very smart.

And don't worry, the order of injecting uses package dependencies.

*I am going to know it closer and will use right now.*

**Comment by larsonjj** [comment]
This had now been added. Check it out in the new [release](https://github.com/larsonjj/generator-yeogurt/releases/tag/v0.13.0)
