### ISSUE TITLE
Dashboard links for modules and pages are incorrect for swig

### ISSUE THREAD

**Issue by fusionstrings** [larsonjj/generator-yeogurt#87]
I tried to generate modules and pages with passing `--folder` parameter.

    yo yeogurt:template components --folder=base --type=module

which generated the file at `client\templates\modules\base\components.swig`.
but in generated swig file, metadata to link it to dashboard creates entry as follows.

    "link": "generated/base//components.html" 

Same goes for page templates

    yo yeogurt:template components --folder=base

generates `client\templates\base\components.swig` with link `"link": "../../base//components.html"`.

Which of course leads to 404 while trying to navigate to page from dashboard.

Also it extends from wrong path `{% extends './layouts/base.swig' %}`, which would have been correct if file would have been generated at root of `templates` folder.

**Comment by larsonjj** [comment]
This should be fixed now in the new [release](https://github.com/larsonjj/generator-yeogurt/releases/tag/v0.13.0)
