### ISSUE TITLE
Change folder structure

### ISSUE THREAD

**Issue by mikaelmoller** [larsonjj/generator-yeogurt#88]
Hi - does anyone know of a good way to change project structure? In my current project I need to maintain my assets in the following order

client
+-- assets
    |   +-- js
|   +-- css
|   +-- less
|   +-- imgs
|   +-- fonts
+-- index.html

**Comment by larsonjj** [comment]
Haven't received a response on this issue for a long time. Hopefully my response helped.

Closing out.
