### ISSUE TITLE
the resulting test after running yo yeogurt:view view-name requires wrong path

### ISSUE THREAD

**Issue by scottjason** [larsonjj/generator-yeogurt#90]
currently running the command:
yo yeogurt:view dashboard results in test/spec/views/dashboard-spec.js with:
var Dashboard = require('../../client/scripts/views/dashboard.js');

Just off by one dir, should be:
var Dashboard = require('../../../client/scripts/views/dashboard.js');

PS Best boilerplate ever!

**Comment by larsonjj** [comment]
Looks like this may be related to #87.
The calculation used to form the folder paths is faulty. I have fixed it for the next version which should be released soon.

Glad to hear you like using Yeogurt :+1:

**Comment by scottjason** [comment]
Thank you Jake!!

Been telling all kinds of bay area devs about the gen. Seriously its great!

I just added two issues. One I think is also related to #87 and there's an
easy quicl temp fix but the other I wasn't able to make it through the
Grunt file. (that thing is a beast!! ha).


Scott

**Comment by larsonjj** [comment]
This should be fixed now in the new [release](https://github.com/larsonjj/generator-yeogurt/releases/tag/v0.13.0)
