### ISSUE TITLE
resource interpreted as script but transferred with mime type text/html

### ISSUE THREAD

**Issue by scottjason** [larsonjj/generator-yeogurt#91]
This may be related to issue #87 and #90.

When creating a new backbone view via the yeogurt command, when this view is initialized this error will throw:

"resource interpreted as script but transferred with mime type text/html"

*The error is only referencing dev styles (bower OK)*

A quick fix for now is to change this :

link rel="stylesheet" href="styles/main.css"

to:

link rel="stylesheet" href="/styles/main.css"

**Comment by larsonjj** [comment]
You were definitely correct on this one, a `/` is needed in front of all assets to be loaded correctly. It should be fixed now in the new [release](https://github.com/larsonjj/generator-yeogurt/releases/tag/v0.13.0)
