### ISSUE TITLE
grunt serve:dist results in JST not defined

### ISSUE THREAD

**Issue by scottjason** [larsonjj/generator-yeogurt#92]
This error I haven't been able to come up with a fix for (gnarly Grunt File!)

**Comment by larsonjj** [comment]
This error was due to a mixup in grunt task order. It should be fixed now in the new [release](https://github.com/larsonjj/generator-yeogurt/releases/tag/v0.13.0)

**Comment by scottjason** [comment]
Awesome!! Thank you so much! We backed up our current build and are yeogurt-ing the new release now!
