### ISSUE TITLE
package.json needs lodash in dependencies

### ISSUE THREAD

**Issue by scottjason** [larsonjj/generator-yeogurt#93]
My buddy at work found this one. After fixing this we were able to deploy the build to Amazon. Just needs lodash added to dependencies (right now it's only in dev dependencies but required in env/config/default.js).

Also, this build is amazing!

**Comment by larsonjj** [comment]
Glad you are getting good use out of the Yeogurt :+1: 

Could you post the contents of the `.yo-rc.json` file located in your project's root folder? It is a hidden file, so you might need to enable hidden files in your file browser first. This will help me pin-point the issue much faster.

Thanks!

**Comment by scottjason** [comment]
Hey Jake, I was never able to get the .yo_rc.json file. I was on my dev machine at home which doesn't have the gitignore files except for config and we ended up doing a couple re-installs . Just wanted to let you know. It's working great!
