### ISSUE TITLE
Option to not include authorization, start clean

### ISSUE THREAD

**Issue by scottjason** [larsonjj/generator-yeogurt#94]
Would be great if there was a way to have this new version of yeogurt, but with an option to not generate all the accounts, messages, auth, etc so it builds just like before but without a huge client-side generated and without all the corresponding server-side logic/files, grunt association to these files, etc. 

Our use case actually does need this stuff but have been having a tough time following some of the client-side Backbone JS. I removed all of this stuff and grunt serve is ok but the generator is throwing an error on the yo:yeogurt command:

---------------------

.node/lib/node_modules/generator-yeogurt/view/index.js:19
  this.useDashboard = fileJSON.useDashboard;

TypeError: Cannot read property 'useDashboard' of undefined at new ViewGenerator (/Users/scottjason/.node/lib/node_modules/generator-yeogurt/view/index.js:19:33)

---------------------

One of the best parts about this generator is all of the options. Also I'll get you that .yo-rc.json file you asked about.

Thanks! (still my fave!)

**Comment by scottjason** [comment]
WHOOPS my bad I just noticed there IS this option!! Just generated and this is exactly what we need! Thank you!!!

**Comment by larsonjj** [comment]
Haha glad you found it :+1: 

Thanks for all the feedback, keep it coming!
