### ISSUE TITLE
App running with  errors

### ISSUE THREAD

**Issue by mvpasarel** [larsonjj/generator-yeogurt#96]
Here is my `.yo-rc.json` https://gist.github.com/mvpasarel/8722f2642494b706d4e4

I am tring to use yeogurt with Backbone and ReactJs but I cant get the app running because of this erros:
http://note.io/1AWBjJd

If I change `define(function()`  to `define(function(require)` in `clients\scripts\views\layouts\default.js` the first error seems fixed but I cant find a solution to the second one.

And here is my folder structure http://note.io/1wb4Sir if helps.

**Comment by larsonjj** [comment]
Hey, thanks for all the info. It helped me debug this very quickly.

It looks like the files generated are incorrect and this is definitely a bug. I updated them with the latest version `v0.13.6` so they should work correctly now.

Please update (`npm install -g generator-yeogurt`) and run the generator again. Let me know if it works for you.

**Comment by mvpasarel** [comment]
Awesome, it works well now! Thank you
